### ISSUE TITLE
Lava and fire damage not hurt any entities anymore!

### ISSUE THREAD

**Issue by huyhhuy1410** [Markus1002/Extra-Boats#65] opened 2023-03-04 08:51 UTC
Mod: Boatload
Mod version: boatload-1.19.2-4.2.0
Versione: Minecraft 1.19.2
Mod loader: Forge 43.2.0
I tried to separate each mod in my 100+ mods folder and test. And I discovered this. This version of this mod broke the fire damage in game.

**Comment by bageldotjpg** [comment] 2023-03-05 21:49
Duplicate of #64

**Closed as completed by bageldotjpg** 2023-03-05 21:49 UTC
